# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!
import rospy
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from std_msgs.msg import Float64

global amplitude
amplitude = 0

class Ui_GaitContorl(object):
    def setupUi(self, GaitContorl):
        GaitContorl.setObjectName("GaitContorl")
        GaitContorl.resize(673, 357)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 611, 261))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(484, 80, 31, 17))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(204, 70, 241, 41))
        self.horizontalSlider_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_6.setMouseTracking(False)
        self.horizontalSlider_6.setMaximum(20)
        self.horizontalSlider_6.setPageStep(4)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_6.setTickInterval(0)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab)
        self.pushButton_14.setGeometry(QtCore.QRect(454, 30, 21, 21))
        self.pushButton_14.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(454, 80, 21, 21))
        self.pushButton_11.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab)
        self.pushButton_12.setGeometry(QtCore.QRect(174, 30, 21, 21))
        self.pushButton_12.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(70, 80, 81, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(70, 30, 81, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(204, 20, 241, 41))
        self.horizontalSlider_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_7.setMouseTracking(False)
        self.horizontalSlider_7.setMaximum(20)
        self.horizontalSlider_7.setPageStep(4)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_7.setTickInterval(0)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab)
        self.pushButton_13.setGeometry(QtCore.QRect(174, 80, 21, 21))
        self.pushButton_13.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(484, 30, 31, 17))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(484, 80, 31, 17))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(484, 30, 31, 17))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(70, 80, 81, 20))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_25.setGeometry(QtCore.QRect(174, 80, 21, 21))
        self.pushButton_25.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_24.setGeometry(QtCore.QRect(174, 30, 21, 21))
        self.pushButton_24.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_24.setObjectName("pushButton_24")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(70, 30, 81, 20))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalSlider_12 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_12.setGeometry(QtCore.QRect(204, 70, 241, 41))
        self.horizontalSlider_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_12.setMouseTracking(False)
        self.horizontalSlider_12.setMaximum(20)
        self.horizontalSlider_12.setPageStep(4)
        self.horizontalSlider_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_12.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_12.setTickInterval(0)
        self.horizontalSlider_12.setObjectName("horizontalSlider_12")
        self.horizontalSlider_13 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_13.setGeometry(QtCore.QRect(204, 20, 241, 41))
        self.horizontalSlider_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_13.setMouseTracking(False)
        self.horizontalSlider_13.setMaximum(20)
        self.horizontalSlider_13.setPageStep(4)
        self.horizontalSlider_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_13.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_13.setTickInterval(0)
        self.horizontalSlider_13.setObjectName("horizontalSlider_13")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_23.setGeometry(QtCore.QRect(454, 80, 21, 21))
        self.pushButton_23.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_26.setGeometry(QtCore.QRect(454, 30, 21, 21))
        self.pushButton_26.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_26.setObjectName("pushButton_26")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalSlider_14 = QtWidgets.QSlider(self.tab_4)
        self.horizontalSlider_14.setGeometry(QtCore.QRect(204, 70, 241, 41))
        self.horizontalSlider_14.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_14.setMouseTracking(False)
        self.horizontalSlider_14.setMaximum(20)
        self.horizontalSlider_14.setPageStep(4)
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_14.setTickInterval(0)
        self.horizontalSlider_14.setObjectName("horizontalSlider_14")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_27.setGeometry(QtCore.QRect(454, 80, 21, 21))
        self.pushButton_27.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_28.setGeometry(QtCore.QRect(174, 30, 21, 21))
        self.pushButton_28.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_28.setObjectName("pushButton_28")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(70, 80, 81, 20))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalSlider_16 = QtWidgets.QSlider(self.tab_4)
        self.horizontalSlider_16.setGeometry(QtCore.QRect(204, 20, 241, 41))
        self.horizontalSlider_16.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_16.setMouseTracking(False)
        self.horizontalSlider_16.setMaximum(20)
        self.horizontalSlider_16.setPageStep(4)
        self.horizontalSlider_16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_16.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_16.setTickInterval(0)
        self.horizontalSlider_16.setObjectName("horizontalSlider_16")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_29.setGeometry(QtCore.QRect(174, 80, 21, 21))
        self.pushButton_29.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(484, 30, 31, 17))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_30.setGeometry(QtCore.QRect(454, 30, 21, 21))
        self.pushButton_30.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_30.setObjectName("pushButton_30")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(70, 30, 81, 20))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(484, 80, 31, 17))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(174, 130, 21, 21))
        self.pushButton_15.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_16.setGeometry(QtCore.QRect(174, 30, 21, 21))
        self.pushButton_16.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(484, 30, 31, 17))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_17.setGeometry(QtCore.QRect(454, 130, 21, 21))
        self.pushButton_17.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(70, 80, 81, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(484, 130, 31, 17))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalSlider_8 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(204, 120, 241, 41))
        self.horizontalSlider_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_8.setMouseTracking(False)
        self.horizontalSlider_8.setMaximum(20)
        self.horizontalSlider_8.setPageStep(4)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_8.setTickInterval(0)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(484, 80, 31, 17))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(484, 180, 31, 17))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(70, 180, 81, 20))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalSlider_9 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(204, 70, 241, 41))
        self.horizontalSlider_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_9.setMouseTracking(False)
        self.horizontalSlider_9.setMaximum(20)
        self.horizontalSlider_9.setPageStep(4)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_9.setTickInterval(0)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.horizontalSlider_10 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(204, 170, 241, 41))
        self.horizontalSlider_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_10.setMouseTracking(False)
        self.horizontalSlider_10.setMaximum(20)
        self.horizontalSlider_10.setPageStep(4)
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_10.setTickInterval(0)
        self.horizontalSlider_10.setObjectName("horizontalSlider_10")
        self.horizontalSlider_11 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(204, 20, 241, 41))
        self.horizontalSlider_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_11.setMouseTracking(False)
        self.horizontalSlider_11.setMaximum(20)
        self.horizontalSlider_11.setPageStep(4)
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_11.setTickInterval(0)
        self.horizontalSlider_11.setObjectName("horizontalSlider_11")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(174, 80, 21, 21))
        self.pushButton_18.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(70, 130, 81, 20))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_19.setGeometry(QtCore.QRect(454, 30, 21, 21))
        self.pushButton_19.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_20.setGeometry(QtCore.QRect(454, 180, 21, 21))
        self.pushButton_20.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_21.setGeometry(QtCore.QRect(174, 180, 21, 21))
        self.pushButton_21.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_22.setGeometry(QtCore.QRect(454, 80, 21, 21))
        self.pushButton_22.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(70, 30, 81, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(484, 130, 31, 17))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalSlider_15 = QtWidgets.QSlider(self.tab_6)
        self.horizontalSlider_15.setGeometry(QtCore.QRect(204, 120, 241, 41))
        self.horizontalSlider_15.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_15.setMouseTracking(False)
        self.horizontalSlider_15.setMaximum(20)
        self.horizontalSlider_15.setPageStep(4)
        self.horizontalSlider_15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_15.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_15.setTickInterval(0)
        self.horizontalSlider_15.setObjectName("horizontalSlider_15")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(484, 30, 31, 17))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_31.setGeometry(QtCore.QRect(454, 130, 21, 21))
        self.pushButton_31.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalSlider_17 = QtWidgets.QSlider(self.tab_6)
        self.horizontalSlider_17.setGeometry(QtCore.QRect(204, 20, 241, 41))
        self.horizontalSlider_17.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_17.setMouseTracking(False)
        self.horizontalSlider_17.setMaximum(20)
        self.horizontalSlider_17.setPageStep(4)
        self.horizontalSlider_17.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_17.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_17.setTickInterval(0)
        self.horizontalSlider_17.setObjectName("horizontalSlider_17")
        self.pushButton_32 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_32.setGeometry(QtCore.QRect(174, 30, 21, 21))
        self.pushButton_32.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_34 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_34.setGeometry(QtCore.QRect(454, 30, 21, 21))
        self.pushButton_34.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_34.setObjectName("pushButton_34")
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setGeometry(QtCore.QRect(70, 130, 81, 20))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.pushButton_33 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_33.setGeometry(QtCore.QRect(174, 130, 21, 21))
        self.pushButton_33.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_33.setObjectName("pushButton_33")
        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setGeometry(QtCore.QRect(74, 37, 71, 20))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(self.tab_6)
        self.label_35.setGeometry(QtCore.QRect(484, 80, 31, 17))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalSlider_18 = QtWidgets.QSlider(self.tab_6)
        self.horizontalSlider_18.setGeometry(QtCore.QRect(204, 70, 241, 41))
        self.horizontalSlider_18.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_18.setMouseTracking(False)
        self.horizontalSlider_18.setMaximum(20)
        self.horizontalSlider_18.setPageStep(4)
        self.horizontalSlider_18.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_18.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_18.setTickInterval(0)
        self.horizontalSlider_18.setObjectName("horizontalSlider_18")
        self.pushButton_35 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_35.setGeometry(QtCore.QRect(174, 80, 21, 21))
        self.pushButton_35.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_36.setGeometry(QtCore.QRect(454, 80, 21, 21))
        self.pushButton_36.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_36.setObjectName("pushButton_36")
        self.label_36 = QtWidgets.QLabel(self.tab_6)
        self.label_36.setGeometry(QtCore.QRect(74, 87, 71, 20))
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(74, 23, 71, 20))
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        self.label_38.setGeometry(QtCore.QRect(74, 73, 71, 20))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_39 = QtWidgets.QLabel(self.tab_5)
        self.label_39.setGeometry(QtCore.QRect(484, 30, 31, 17))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalSlider_19 = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_19.setGeometry(QtCore.QRect(204, 120, 241, 41))
        self.horizontalSlider_19.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_19.setMouseTracking(False)
        self.horizontalSlider_19.setMaximum(20)
        self.horizontalSlider_19.setPageStep(4)
        self.horizontalSlider_19.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_19.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_19.setTickInterval(0)
        self.horizontalSlider_19.setObjectName("horizontalSlider_19")
        self.horizontalSlider_20 = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_20.setGeometry(QtCore.QRect(204, 20, 241, 41))
        self.horizontalSlider_20.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_20.setMouseTracking(False)
        self.horizontalSlider_20.setMaximum(20)
        self.horizontalSlider_20.setPageStep(4)
        self.horizontalSlider_20.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_20.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_20.setTickInterval(0)
        self.horizontalSlider_20.setObjectName("horizontalSlider_20")
        self.pushButton_37 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_37.setGeometry(QtCore.QRect(454, 130, 21, 21))
        self.pushButton_37.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_38.setGeometry(QtCore.QRect(174, 30, 21, 21))
        self.pushButton_38.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_39.setGeometry(QtCore.QRect(454, 30, 21, 21))
        self.pushButton_39.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_39.setObjectName("pushButton_39")
        self.label_40 = QtWidgets.QLabel(self.tab_5)
        self.label_40.setGeometry(QtCore.QRect(484, 80, 31, 17))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_5)
        self.label_41.setGeometry(QtCore.QRect(74, 23, 71, 20))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_5)
        self.label_42.setGeometry(QtCore.QRect(70, 130, 81, 20))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.pushButton_40 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_40.setGeometry(QtCore.QRect(454, 80, 21, 21))
        self.pushButton_40.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_40.setObjectName("pushButton_40")
        self.label_43 = QtWidgets.QLabel(self.tab_5)
        self.label_43.setGeometry(QtCore.QRect(74, 73, 71, 20))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.pushButton_41 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_41.setGeometry(QtCore.QRect(174, 130, 21, 21))
        self.pushButton_41.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_41.setObjectName("pushButton_41")
        self.label_44 = QtWidgets.QLabel(self.tab_5)
        self.label_44.setGeometry(QtCore.QRect(74, 37, 71, 20))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_5)
        self.label_45.setGeometry(QtCore.QRect(484, 130, 31, 17))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalSlider_21 = QtWidgets.QSlider(self.tab_5)
        self.horizontalSlider_21.setGeometry(QtCore.QRect(204, 70, 241, 41))
        self.horizontalSlider_21.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider_21.setMouseTracking(False)
        self.horizontalSlider_21.setMaximum(20)
        self.horizontalSlider_21.setPageStep(4)
        self.horizontalSlider_21.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_21.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_21.setTickInterval(0)
        self.horizontalSlider_21.setObjectName("horizontalSlider_21")
        self.pushButton_42 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_42.setGeometry(QtCore.QRect(174, 80, 21, 21))
        self.pushButton_42.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_42.setObjectName("pushButton_42")
        self.label_46 = QtWidgets.QLabel(self.tab_5)
        self.label_46.setGeometry(QtCore.QRect(74, 87, 71, 20))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.tabWidget.addTab(self.tab_5, "")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(30, 290, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 290, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 290, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 290, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        GaitContorl.setWidget(self.dockWidgetContents)

        self.retranslateUi(GaitContorl)
        self.tabWidget.setCurrentIndex(3)
        self.horizontalSlider_7.valueChanged['int'].connect(self.label_12.setNum)
        self.horizontalSlider_6.valueChanged['int'].connect(self.label_14.setNum)
        self.horizontalSlider_13.valueChanged['int'].connect(self.label_24.setNum)
        self.horizontalSlider_12.valueChanged['int'].connect(self.label_26.setNum)
        self.horizontalSlider_16.valueChanged['int'].connect(self.label_28.setNum)
        self.horizontalSlider_14.valueChanged['int'].connect(self.label_30.setNum)
        self.horizontalSlider_11.valueChanged['int'].connect(self.label_15.setNum)
        self.horizontalSlider_9.valueChanged['int'].connect(self.label_18.setNum)
        self.horizontalSlider_8.valueChanged['int'].connect(self.label_17.setNum)
        self.horizontalSlider_10.valueChanged['int'].connect(self.label_19.setNum)
        self.horizontalSlider_17.valueChanged['int'].connect(self.label_32.setNum)
        self.horizontalSlider_18.valueChanged['int'].connect(self.label_35.setNum)
        self.horizontalSlider_15.valueChanged['int'].connect(self.label_34.setNum)
        self.horizontalSlider_20.valueChanged['int'].connect(self.label_39.setNum)
        self.horizontalSlider_21.valueChanged['int'].connect(self.label_40.setNum)
        self.horizontalSlider_19.valueChanged['int'].connect(self.label_45.setNum)

        self.pushButton_2.clicked.connect(self.quit_button)

        QtCore.QMetaObject.connectSlotsByName(GaitContorl)

    def retranslateUi(self, GaitContorl):
        _translate = QtCore.QCoreApplication.translate
        GaitContorl.setWindowTitle(_translate("GaitContorl", "GaitContorl"))
        self.label_14.setText(_translate("GaitContorl", "0"))
        self.pushButton_14.setText(_translate("GaitContorl", "+"))
        self.pushButton_11.setText(_translate("GaitContorl", "+"))
        self.pushButton_12.setText(_translate("GaitContorl", "-"))
        self.label_11.setText(_translate("GaitContorl", "Frequency"))
        self.label_13.setText(_translate("GaitContorl", "Amplitude"))
        self.pushButton_13.setText(_translate("GaitContorl", "-"))
        self.label_12.setText(_translate("GaitContorl", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GaitContorl", "Rolling"))
        self.label_26.setText(_translate("GaitContorl", "0"))
        self.label_24.setText(_translate("GaitContorl", "0"))
        self.label_23.setText(_translate("GaitContorl", "Frequency"))
        self.pushButton_25.setText(_translate("GaitContorl", "-"))
        self.pushButton_24.setText(_translate("GaitContorl", "-"))
        self.label_25.setText(_translate("GaitContorl", "Amplitude"))
        self.pushButton_23.setText(_translate("GaitContorl", "+"))
        self.pushButton_26.setText(_translate("GaitContorl", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("GaitContorl", "Sidewinding"))
        self.pushButton_27.setText(_translate("GaitContorl", "+"))
        self.pushButton_28.setText(_translate("GaitContorl", "-"))
        self.label_27.setText(_translate("GaitContorl", "Frequency"))
        self.pushButton_29.setText(_translate("GaitContorl", "-"))
        self.label_28.setText(_translate("GaitContorl", "0"))
        self.pushButton_30.setText(_translate("GaitContorl", "+"))
        self.label_29.setText(_translate("GaitContorl", "Amplitude"))
        self.label_30.setText(_translate("GaitContorl", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("GaitContorl", "Vertical"))
        self.pushButton_15.setText(_translate("GaitContorl", "-"))
        self.pushButton_16.setText(_translate("GaitContorl", "-"))
        self.label_15.setText(_translate("GaitContorl", "0"))
        self.pushButton_17.setText(_translate("GaitContorl", "+"))
        self.label_16.setText(_translate("GaitContorl", "Frequency"))
        self.label_17.setText(_translate("GaitContorl", "0"))
        self.label_18.setText(_translate("GaitContorl", "0"))
        self.label_19.setText(_translate("GaitContorl", "0"))
        self.label_20.setText(_translate("GaitContorl", "Nu"))
        self.pushButton_18.setText(_translate("GaitContorl", "-"))
        self.label_21.setText(_translate("GaitContorl", "Phi"))
        self.pushButton_19.setText(_translate("GaitContorl", "+"))
        self.pushButton_20.setText(_translate("GaitContorl", "+"))
        self.pushButton_21.setText(_translate("GaitContorl", "-"))
        self.pushButton_22.setText(_translate("GaitContorl", "+"))
        self.label_22.setText(_translate("GaitContorl", "Amplitude"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GaitContorl", "Pipe-Crawling"))
        self.label_34.setText(_translate("GaitContorl", "0"))
        self.label_32.setText(_translate("GaitContorl", "0"))
        self.pushButton_31.setText(_translate("GaitContorl", "+"))
        self.pushButton_32.setText(_translate("GaitContorl", "-"))
        self.pushButton_34.setText(_translate("GaitContorl", "+"))
        self.label_31.setText(_translate("GaitContorl", "Frequency"))
        self.pushButton_33.setText(_translate("GaitContorl", "-"))
        self.label_33.setText(_translate("GaitContorl", "Amplitude"))
        self.label_35.setText(_translate("GaitContorl", "0"))
        self.pushButton_35.setText(_translate("GaitContorl", "-"))
        self.pushButton_36.setText(_translate("GaitContorl", "+"))
        self.label_36.setText(_translate("GaitContorl", "Amplitude"))
        self.label_37.setText(_translate("GaitContorl", "Vertical"))
        self.label_38.setText(_translate("GaitContorl", "Horizontal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("GaitContorl", "Sinuslifting"))
        self.label_39.setText(_translate("GaitContorl", "0"))
        self.pushButton_37.setText(_translate("GaitContorl", "+"))
        self.pushButton_38.setText(_translate("GaitContorl", "-"))
        self.pushButton_39.setText(_translate("GaitContorl", "+"))
        self.label_40.setText(_translate("GaitContorl", "0"))
        self.label_41.setText(_translate("GaitContorl", "Vertical"))
        self.label_42.setText(_translate("GaitContorl", "Frequency"))
        self.pushButton_40.setText(_translate("GaitContorl", "+"))
        self.label_43.setText(_translate("GaitContorl", "Horizontal"))
        self.pushButton_41.setText(_translate("GaitContorl", "-"))
        self.label_44.setText(_translate("GaitContorl", "Amplitude"))
        self.label_45.setText(_translate("GaitContorl", "0"))
        self.pushButton_42.setText(_translate("GaitContorl", "-"))
        self.label_46.setText(_translate("GaitContorl", "Amplitude"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("GaitContorl", "Rotating"))
        self.pushButton.setText(_translate("GaitContorl", "Apply"))
        self.pushButton_2.setText(_translate("GaitContorl", "Quit"))
        self.pushButton_3.setText(_translate("GaitContorl", "Stretch"))
        self.pushButton_4.setText(_translate("GaitContorl", "Init_pose"))

    def quit_button(self):
        QtCore.QCoreApplication.instance().quit()
        rospy.signal_shutdown("Quit the slider")

def talker():
    global amplitude
    pub = rospy.Publisher('amp', Float64, queue_size=10)
    while not rospy.is_shutdown():
        global amplitude
        pub.publish(float(amplitude))
        rospy.sleep(0.1)

def talker_thread():
    print('Start to publish Amplitude to ROS core...')
    t_thread = threading.Thread(target = talker)
    t_thread.start()

if __name__ == "__main__":
    import sys
    rospy.init_node('gaitparam_talker')
    talker_thread()
    app = QtWidgets.QApplication(sys.argv)
    GaitContorl = QtWidgets.QDockWidget()
    ui = Ui_GaitContorl()
    ui.setupUi(GaitContorl)
    GaitContorl.show()
    sys.exit(app.exec_())
    rospy.signal_shutdown("Quit the slider")
